name: Update charts on bucket

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run build
        run: go run . -member ${{ secrets.BSPORT_MEMBER }} -token ${{ secrets.BSPORT_TOKEN }}
      - name: install mc
        run: curl -O https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc
      - name: configure mc
        run: "./mc config host add scw https://s3.fr-par.scw.cloud  ${{ secrets.SCW_ACCESS_KEY }} ${{ secrets.SCW_SECRET_KEY }} --api S3v4"
      - name: deploy to object storage
        run: ./mc cp charts.html scw/bsport-charts/index.html
